### ISSUE TITLE
Caret coordinates are always "-1, -1"

### ISSUE THREAD

**Issue by zachpoblete** [zero-plusplus/vscode-operate-from-autohotkey#17]
# Steps
1. Clone this [repo](https://github.com/KingQuarter/GetVsCodeCaret).
2. Set `operate-from-autohotkey.externalLibrary.acc` to the path where Acc.ahk is in.
3. Run GetVsCodeCaret.ahk.
4. Press F1 to execute `operate-from-autohotkey.copy.context.caret.coordinates`. This command should get the caret coordinates, but it always returns "-1, -1".
5. Press F2 to call `GetCaret`. This function successfully returns the coordinates this time. GetCaret is a function I found on the forums that also depends on Acc.ahk. 

# Specifics
AutoHotkey: 1.1.34.03
VSCode: 1.70.2 (user setup)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

# Notes
I probably went wrong somewhere. Please help me out if I did!

**Comment by zero-plusplus** [comment]
Thanks for the report.

I have checked the following environment and was able to retrieve the values without any problems.

1. Clone to desktop folder on Windows Sandbox
2. The path I set for `operate-from-autohotkey.externalLibrary.acc` is `C:\Users\WDAGUtilityAccount\Desktop\GetVsCodeCaret-main\Acc.ahk`.
  NOTE: `WDAGUtilityAccount` is the username on the sandbox. Replace it with your own username.
3. Run `GetVsCodeCaret.ahk` and check

Check if the same problem occurs when you set up Acc.ahk as above.

**Comment by zachpoblete** [comment]
I never tried your steps, but I no longer use this script, so I'll close the issue.

**Comment by zero-plusplus** [comment]
The following library, which was created in the prototype of this extension, can be used to obtain information on the x, y, width and height of the caret (Currently only AutoHotkey v1 version is supported).

* https://github.com/zero-plusplus/vscode-operate-from-autohotkey/blob/v2.0.0-develop/demo/lib/GetCaretRect.ahk

Like Acc.ahk, it uses the Windows API and can be used to identify the caret position in applications (e.g. vscode) that cannot be obtained using AutoHotkey's A_CaretX and A_CaretY.
